[project]
name = "mcp-robot2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cadquery>=2.5.2",
    "mcp[cli]>=1.12.0",
    "pyglet==1.5.28",
    "pyribbit==0.1.46",
    "urchin>=0.0.29",
    "yourdfpy>=0.0.58",
]
